### ISSUE TITLE
tree_sitter_ocamllex doesn't compile with latest tree-sitter (0.20.3)

### ISSUE THREAD

**Issue by carlosala** [nvim-treesitter/nvim-treesitter#2340]
### Describe the bug

`tree-sitter` has recently updated it's library and ocamllex parser doesn't compile.

### To Reproduce

1. Open neovim
2. Try to install `ocamllex` parser
3. Exception raises:
```
nvim-treesitter[ocamllex]: Error during compilation                                                                                                                                            
src/parser.c: In function ‘tree_sitter_ocamllex’:                                                                                                                                              
src/parser.c:2769:6: error: ‘TSLanguage’ has no member named ‘state_count’                                                                                                                     
 2769 |     .state_count = STATE_COUNT,                                                                                                                                                        
      |      ^~~~~~~~~~~                                                                                                                                                                       
src/parser.c:9:21: warning: initialization of ‘const char **’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]                                                          
    9 | #define STATE_COUNT 98                                                                                                                                                                 
      |                     ^~                                                                                                                                                                 
src/parser.c:2769:20: note: in expansion of macro ‘STATE_COUNT’                                                                                                                                
 2769 |     .state_count = STATE_COUNT,                                                                                                                                                        
      |                    ^~~~~~~~~~~                                                                                                                                                         
src/parser.c:9:21: note: (near initialization for ‘language.symbol_names’)                                                                                                                     
    9 | #define STATE_COUNT 98                                                                                                                                                                 
      |                     ^~                                                                                                                                                                 
src/parser.c:2769:20: note: in expansion of macro ‘STATE_COUNT’                                                                                                                                
 2769 |     .state_count = STATE_COUNT,                                                                                                                                                        
      |                    ^~~~~~~~~~~                                                                                                                                                         
src/parser.c:2771:6: error: ‘TSLanguage’ has no member named ‘production_id_count’                                                                                                             
 2771 |     .production_id_count = PRODUCTION_ID_COUNT,                                                                                                                                        
      |      ^~~~~~~~~~~~~~~~~~~                                                                                                                                                               
src/parser.c:17:29: warning: initialization of ‘const uint16_t *’ {aka ‘const short unsigned int *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]                   
   17 | #define PRODUCTION_ID_COUNT 3                                                                                                                                                          
      |                             ^                                                                                                                                                          
src/parser.c:2771:28: note: in expansion of macro ‘PRODUCTION_ID_COUNT’                                                                                                                        
 2771 |     .production_id_count = PRODUCTION_ID_COUNT,                                                                                                                                        
      |                            ^~~~~~~~~~~~~~~~~~~                                                                                                                                         
src/parser.c:17:29: note: (near initialization for ‘language.small_parse_table’)                                                                                                               
   17 | #define PRODUCTION_ID_COUNT 3                                                                                                                                                          
      |                             ^                                                                                                                                                          
src/parser.c:2771:28: note: in expansion of macro ‘PRODUCTION_ID_COUNT’                                                                                                                        
 2771 |     .production_id_count = PRODUCTION_ID_COUNT,                                                                                                                                        
      |                            ^~~~~~~~~~~~~~~~~~~                                                                                                                                         
src/parser.c:2778:21: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]                                                                     
 2778 |     .symbol_names = ts_symbol_names,                                                                                                                                                   
      |                     ^~~~~~~~~~~~~~~                                                                                                                                                    
src/parser.c:2781:6: error: ‘TSLanguage’ has no member named ‘alias_map’                                                                                                                       
 2781 |     .alias_map = ts_non_terminal_alias_map,                                                                                                                                            
      |      ^~~~~~~~~                                                                                                                                                                         
src/parser.c:2781:18: warning: excess elements in struct initializer                                                                                                                           
 2781 |     .alias_map = ts_non_terminal_alias_map,                                                                                                                                            
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                             
src/parser.c:2781:18: note: (near initialization for ‘language’)                                                                                                                               
```

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.3 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.13.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - beancount      ✓ . ✓ . . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - ninja          ✓ . ✓ ✓ . 
  - ql             ✓ ✓ . ✓ ✓ 
  - glsl           ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - pug            ✓ . . . ✓ 
  - ledger         ✓ . ✓ ✓ ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - hack           ✓ . . . . 
  - heex           ✓ . ✓ ✓ ✓ 
  - godot_resource ✓ ✓ ✓ . . 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - vue            ✓ . ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - make           ✓ . . . ✓ 
  - rst            ✓ ✓ . . ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - glimmer        ✓ . . . . 
  - erlang         . . . . . 
  - gowork         ✓ . . . ✓ 
  - regex          ✓ . . . . 
  - nix            ✓ ✓ ✓ . ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - elm            ✓ . . . ✓ 
  - prisma         ✓ . . . . 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - fortran        ✓ . ✓ ✓ . 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - http           ✓ . . . ✓ 
  - llvm           ✓ . . . . 
  - d              ✓ . ✓ ✓ ✓ 
  - hjson          ✓ ✓ ✓ ✓ ✓ 
  - gomod          ✓ . . . ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - verilog        ✓ ✓ ✓ . ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - pioasm         ✓ . . . ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - json5          ✓ . . . ✓ 
  - vim            ✓ ✓ . . ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - zig            ✓ . ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - r              ✓ ✓ . . . 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - devicetree     ✓ ✓ ✓ ✓ ✓ 
  - jsdoc          ✓ . . . . 
  - gdscript       ✓ ✓ . . ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - pascal         ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - fusion         ✓ ✓ ✓ ✓ . 
  - scss           ✓ . . ✓ . 
  - yang           ✓ . ✓ . . 
  - hocon          ✓ . . . ✓ 
  - surface        ✓ . ✓ ✓ ✓ 
  - swift          ✓ ✓ . . . 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - dot            ✓ . . . ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - kotlin         ✓ ✓ ✓ . ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - scala          ✓ . ✓ . ✓ 
  - dockerfile     ✓ . . . ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - haskell        ✓ . . . ✓ 
  - perl           ✓ . . . . 
  - tlaplus        ✓ . ✓ . ✓ 
  - markdown       ✓ . ✓ . ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - foam           ✓ ✓ ✓ ✓ ✓ 
  - rasi           ✓ ✓ ✓ ✓ . 
  - hcl            ✓ . ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}


   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Output of `nvim --version`

```text
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
Looks like the upstream parser is not compatible. Can you try `:TSInstallFromGrammar ocamllex`? That works for me.

**Comment by theHamsta** [comment]
Happens also to me when I don't use the tree-sitter-cli from npm. So normally, I'd get the same error as reported in the issue but not when I use the tree-sitter-cli (probably older) in their package.json via
```
export PATH=~/node_modules/.bin:$PATH
export PATH=./node_modules/.bin:$PATH
```
Maybe related to miss-match in parser.h

**Comment by clason** [comment]
Ah, tree-sitter mismatch due to NPM is a possibility. We need to put this on the "gotcha" list for the troubleshooting document.

**Comment by carlosala** [comment]
> Looks like the upstream parser is not compatible. Can you try `:TSInstallFromGrammar ocamllex`? That works for me.

not working here

**Comment by theHamsta** [comment]
@clason the problem is the new cli. The one from npm works.

**Comment by clason** [comment]
The new CLI _must_ be run with an `--abi` flag, which is what nvim-treesitter now does when the new version is found first. I can install `ocamllex` just fine from within Neovim, so there must be some other difference responsible.

**Comment by carlosala** [comment]
Now I see that there's a bug reported in the neovim package for arch (which I use) that luajit version used is 2.0.5 instead of 2.1.0beta3, which is used in neovim releases. Maybe could be this

**Comment by theHamsta** [comment]
It's now working also with 0.20.3 for me. I used a tree-sitter-cli a few days before the tagged release.

**Comment by carlosala** [comment]
When I have the tree-sitter arch package installed it doesn't work, and when I remove it works perfectly. Same happens with phpdoc

**Comment by carlosala** [comment]
> When I have the tree-sitter arch package installed it doesn't work, and when I remove it works perfectly. Same happens with phpdoc

I confirm that this is the problem. I downgraded to tree-sitter v0.20.2 and everything compiles. Seems like some library is not working well. I also tried the nightly version of nvim with v0.20.3 and everything compiles, so I deduce that the incompatibility is with neovim stable and tree-sitter v0.20.3

**Comment by clason** [comment]
Indeed, the combination Neovim stable + tree-sitter CLI v0.20.3 does not like this parser. Weird.

**Comment by carlosala** [comment]
yes, it's quite weird. Someone should post an issue in the neovim repo and tree-sitter repo to understand what's happening

**Comment by clason** [comment]
No, this has nothing to do with Neovim; parser installation is only handled by this plugin.

**Comment by clason** [comment]
I think I may see the problem: If I clone the repo and to `tree-sitter generate --abi=13` (with the latest version), `tree-sitter test` doesn't complete. It only does when I `tree-sitter generate --abi=14`.

This is either a tree-sitter regression (@maxbrunsfeld?) or a parser issue.

**Comment by maxbrunsfeld** [comment]
@clason I can't reproduce this; the ocamllex tests run fine for me with both ABIs.

**Comment by clason** [comment]
Interesting. Here's the output on my side (macOS):
```
Parser compilation failed.
Stdout:
Stderr: /Users/clason/build/tree-sitter-ocamllex/src/scanner.cc:14:18: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
  bool in_string = false;
                 ^
1 warning generated.
/Users/clason/build/tree-sitter-ocamllex/src/parser.c:2769:6: error: field designator 'state_count' does not refer to any field in type 'const TSLanguage' (aka 'const struct TSLanguage')
    .state_count = STATE_COUNT,
     ^
/Users/clason/build/tree-sitter-ocamllex/src/parser.c:2771:6: error: field designator 'production_id_count' does not refer to any field in type 'const TSLanguage' (aka 'const struct TSLanguage')
    .production_id_count = PRODUCTION_ID_COUNT,
     ^
/Users/clason/build/tree-sitter-ocamllex/src/parser.c:2778:21: warning: initializing 'const char **' with an expression of type 'const char *const [65]' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    .symbol_names = ts_symbol_names,
                    ^~~~~~~~~~~~~~~
/Users/clason/build/tree-sitter-ocamllex/src/parser.c:2781:6: error: field designator 'alias_map' does not refer to any field in type 'const TSLanguage' (aka 'const struct TSLanguage')
    .alias_map = ts_non_terminal_alias_map,
     ^
1 warning and 3 errors generated.
```

**Comment by maxbrunsfeld** [comment]
Oh, I see - it's because of the `parser.h` not being generated, as you mentioned to me earlier. I thought you were seeing some kind of hang or infinite loop when running the tests themselves. I'm gonna publish a new release of the CLI that always generated the header file.

**Comment by clason** [comment]
Yes, sorry, that was poorly phrased, I realize now.

**Comment by maxbrunsfeld** [comment]
No worries! I just wanted to check that there wasn't some other regression before I publish another patch release.

**Comment by clason** [comment]
Really appreciate it!

Let's see if that makes CI happy ;)

**Comment by carlosala** [comment]
now it works great, I tried all combinations of neovim and tree-sitter and everything is OK

**Comment by andrestone** [comment]
Still failing here. Same error.

**Comment by clason** [comment]
Did you update the tree-sitter CLI to 0.20.4, nvim-treesitter to the latest commit, and ran `:TSInstall ocamllex`?

**Comment by andrestone** [comment]
Forgot to update the CLI. It works fine now. Thanks.
